[package]
name = "raytracer_codegen"
version = "0.1.0"
authors = ["Haoyuan Liu"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
